version: "3.1"

services:
  app:
    build:
      context: .
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - APP_URL=${APP_URL}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
      # set the GOOGLE_APPLICATION_CREDENTIALS env variable to the path of the gcloud.json file
      - $HOME/gcloud.json:/app/gcloud.json
